import "./globals.css";
import NavBar from "../components/navbar";
import Providers from "./providers";
import Head from "next/head";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>Myxellia Interview Test</title>
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <link
          href="https://fonts.cdnfonts.com/css/euclid-circular-b"
          rel="stylesheet"
        ></link>
      </Head>
      <body>
        <Providers>
          <NavBar />
          {children}
         
        </Providers>
      </body>
    </html>
  );
}
